services:
  - type: web
    name: safety-app-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_HOST
        sync: false
      - key: DATABASE_PORT
        sync: false
      - key: DATABASE_USER
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: SECRET_KEY
        value: CFZMstvSDVBlSotkdG_K0G9hNhiUKAETi1g499hB9vw
      - key: ENCRYPTION_KEY
        value: ZX8ei0vVzu3lIGn54PFPmcsHtwtFkxHWCclIdYLZ0uk
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: CORS_ORIGINS
        value: "*"
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        fromGroup: web
